### ISSUE TITLE
Fade in real content

### ISSUE THREAD

**Issue by kodeine** [o-rango/o-content-placeholder#12]
Is it possible to fade out placeholder and show real content this way if being used on angular we dont have to use *ngIf. we can pass real text or image along with it.

**Comment by romulocintra** [comment]
Hi @kodeine 

If i understood your question , in case you are using angular you can simply have

```
@Component({
  selector: 'ng-if-else',
  template: ` 
    <div *ngIf="loading; else elseBlock">
      <o-content-placeholder-img size="55" animate="true" format="square"/>
      <o-content-placeholder-img size="55" animate="false" format="circle"/>
    </div>
    <ng-template #elseBlock>Loaded Content</ng-template>
   `
})
```
And you can add any animation fade etc on this ...
